### ISSUE TITLE
Toggling sort order "generates" a new LC

### ISSUE THREAD

**Issue by gobater** [mbehr1/dlt-logs#115]
On v1.56.1, toggling the sort order will re-run the Lifecycle detection analysis and append them to the list (instead of replacing the previously detected)

See screenshot:
![image](https://user-images.githubusercontent.com/23657567/200570522-04cd611a-a1d3-4d60-9d18-051de69e5fa7.png)

In the picture above, the button "toggle sort order" was pressed 6 times

**Comment by mbehr1** [comment]
Oh. Thanks for the bug report, Jordi! Will analyse and try to provide a fix soon (next weekend).

**Comment by mbehr1** [comment]
fixed with v1.56.2. @gobater please check and confirm (close) if ok. thx!

**Comment by gobater** [comment]
Thanks for fixing @mbehr1 . Problem solved in v1.56.2
