### ISSUE TITLE
Support for online logs

### ISSUE THREAD

**Issue by ocducs** [mbehr1/dlt-logs#121]
Is there a workaround to use the extension with a living log file? not dlt-daemon client wich seems a more little work...

**Comment by ocducs** [comment]
Sorry I was thinking in a pull request..

**Comment by mbehr1** [comment]
I prepared parts of the code base for live logging. Which source (tcp, udp, serial) would you be interested in?
My main target for that feature would be live graphical reports and live updates for badges via fishbone charts.

**Comment by ocducs** [comment]
Absolutelly, I am handling serial and tcp.
Do you have a draft about that feature? It could be interestesting, and even if you dont have a final I will be also interested in learn about it.

Fishbone charts are also the great part!
