### ISSUE TITLE
Visualize single events in graph

### ISSUE THREAD

**Issue by jschmer** [mbehr1/dlt-logs#3]
It would be nice if you could visualize single events in the graph, similar to the green Lifecycle vertical lines but with custom string matches.

**Comment by mbehr1** [comment]
will add it to next release using scatter graphs first. (see chart.js scatter graphs for a sample https://www.chartjs.org/samples/latest/charts/scatter/basic.html ).

**Comment by mbehr1** [comment]
I have a first version with "scatter" charts ready. But I dislike that I "encode" the type of chart in the name (currently I added "EVENT_" similar to "STATE_" and "INT_"). I'm thinking about a more versatile/generic way to add these kind of parameters/attributes (e.g. as parameters within "reportOptions" but its not so easy as a regex or conversionFunction can return multiple values with different types and not even the order is fixed...). Need to think about it first ;-)

**Comment by mbehr1** [comment]
@jschmer implemented in v0.29.0. Updated docs as well. Let me know whether that works for you.

**Comment by jschmer** [comment]
Thanks! Works okay for me.
